// Code generated by protoc-gen-go. DO NOT EDIT.
// source: users/server/proto/users.proto

package go_micro_srv_users

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Nickname             string   `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_users_625c9ae543479a36, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

type GetRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_users_625c9ae543479a36, []int{1}
}
func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (dst *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(dst, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Users struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Users) Reset()         { *m = Users{} }
func (m *Users) String() string { return proto.CompactTextString(m) }
func (*Users) ProtoMessage()    {}
func (*Users) Descriptor() ([]byte, []int) {
	return fileDescriptor_users_625c9ae543479a36, []int{2}
}
func (m *Users) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Users.Unmarshal(m, b)
}
func (m *Users) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Users.Marshal(b, m, deterministic)
}
func (dst *Users) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Users.Merge(dst, src)
}
func (m *Users) XXX_Size() int {
	return xxx_messageInfo_Users.Size(m)
}
func (m *Users) XXX_DiscardUnknown() {
	xxx_messageInfo_Users.DiscardUnknown(m)
}

var xxx_messageInfo_Users proto.InternalMessageInfo

func (m *Users) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "go.micro.srv.users.User")
	proto.RegisterType((*GetRequest)(nil), "go.micro.srv.users.GetRequest")
	proto.RegisterType((*Users)(nil), "go.micro.srv.users.Users")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for UserService service

type UserServiceClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*Users, error)
}

type userServiceClient struct {
	c           client.Client
	serviceName string
}

func NewUserServiceClient(serviceName string, c client.Client) UserServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.users"
	}
	return &userServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *userServiceClient) Get(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*Users, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.Get", in)
	out := new(Users)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceHandler interface {
	Get(context.Context, *GetRequest, *Users) error
}

func RegisterUserServiceHandler(s server.Server, hdlr UserServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&UserService{hdlr}, opts...))
}

type UserService struct {
	UserServiceHandler
}

func (h *UserService) Get(ctx context.Context, in *GetRequest, out *Users) error {
	return h.UserServiceHandler.Get(ctx, in, out)
}

func init() {
	proto.RegisterFile("users/server/proto/users.proto", fileDescriptor_users_625c9ae543479a36)
}

var fileDescriptor_users_625c9ae543479a36 = []byte{
	// 248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x50, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0x26, 0x49, 0x2b, 0x3a, 0x45, 0x85, 0x01, 0x21, 0x86, 0x52, 0x42, 0x4e, 0x39, 0xed, 0x42,
	0x3d, 0xf8, 0x06, 0xf6, 0x1e, 0x11, 0xcf, 0x69, 0x32, 0x86, 0x45, 0xb3, 0x5b, 0x77, 0x36, 0xb9,
	0x88, 0x17, 0x5f, 0xc1, 0x47, 0xf3, 0x15, 0x7c, 0x10, 0xc9, 0x28, 0x0a, 0x6a, 0x6f, 0x33, 0xdf,
	0xcc, 0xf7, 0xc3, 0x07, 0xab, 0x81, 0xc9, 0xb3, 0x66, 0xf2, 0x23, 0x79, 0xbd, 0xf3, 0x2e, 0x38,
	0x2d, 0x90, 0x92, 0x19, 0xb1, 0x73, 0xaa, 0x37, 0x8d, 0x77, 0x8a, 0xfd, 0xa8, 0xe4, 0x92, 0x2d,
	0x3b, 0xe7, 0xba, 0x07, 0xd2, 0xf5, 0xce, 0xe8, 0xda, 0x5a, 0x17, 0xea, 0x60, 0x9c, 0xfd, 0x62,
	0x14, 0x57, 0x30, 0xbb, 0x61, 0xf2, 0x78, 0x02, 0xb1, 0x69, 0xd3, 0x28, 0x8f, 0xca, 0xa4, 0x8a,
	0x4d, 0x8b, 0x08, 0x33, 0x5b, 0xf7, 0x94, 0xc6, 0x79, 0x54, 0x1e, 0x55, 0x32, 0x63, 0x06, 0x87,
	0xd6, 0x34, 0xf7, 0x82, 0x27, 0x82, 0x7f, 0xef, 0xc5, 0x12, 0x60, 0x43, 0xa1, 0xa2, 0xc7, 0x81,
	0x38, 0xfc, 0x56, 0x2b, 0x2e, 0x61, 0x3e, 0xb9, 0x30, 0x2a, 0x98, 0x4b, 0xaa, 0x34, 0xca, 0x93,
	0x72, 0xb1, 0x4e, 0xd5, 0xdf, 0xc0, 0x6a, 0xfa, 0xac, 0x3e, 0xdf, 0xd6, 0x77, 0xb0, 0x98, 0xd6,
	0x6b, 0xf2, 0xa3, 0x69, 0x08, 0x6f, 0x21, 0xd9, 0x50, 0xc0, 0xd5, 0x7f, 0xb4, 0x1f, 0xfb, 0xec,
	0x7c, 0x9f, 0x2c, 0x17, 0x67, 0x2f, 0x6f, 0xef, 0xaf, 0xf1, 0x29, 0x1e, 0xeb, 0x9e, 0xfa, 0xed,
	0x54, 0xe6, 0x93, 0x69, 0x9f, 0xb7, 0x07, 0xd2, 0xc6, 0xc5, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xa0, 0x95, 0xe3, 0xca, 0x61, 0x01, 0x00, 0x00,
}
