// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gateway/proto/users.proto

package go_micro_srv_users

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Nickname             string   `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_users_421b83fab0ec31a4, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

type GetRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_users_421b83fab0ec31a4, []int{1}
}
func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (dst *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(dst, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Users struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Users) Reset()         { *m = Users{} }
func (m *Users) String() string { return proto.CompactTextString(m) }
func (*Users) ProtoMessage()    {}
func (*Users) Descriptor() ([]byte, []int) {
	return fileDescriptor_users_421b83fab0ec31a4, []int{2}
}
func (m *Users) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Users.Unmarshal(m, b)
}
func (m *Users) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Users.Marshal(b, m, deterministic)
}
func (dst *Users) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Users.Merge(dst, src)
}
func (m *Users) XXX_Size() int {
	return xxx_messageInfo_Users.Size(m)
}
func (m *Users) XXX_DiscardUnknown() {
	xxx_messageInfo_Users.DiscardUnknown(m)
}

var xxx_messageInfo_Users proto.InternalMessageInfo

func (m *Users) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "go.micro.srv.users.User")
	proto.RegisterType((*GetRequest)(nil), "go.micro.srv.users.GetRequest")
	proto.RegisterType((*Users)(nil), "go.micro.srv.users.Users")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Users, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Users, error) {
	out := new(Users)
	err := c.cc.Invoke(ctx, "/go.micro.srv.users.UserService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	Get(context.Context, *GetRequest) (*Users, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.users.UserService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "go.micro.srv.users.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _UserService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateway/proto/users.proto",
}

func init() { proto.RegisterFile("gateway/proto/users.proto", fileDescriptor_users_421b83fab0ec31a4) }

var fileDescriptor_users_421b83fab0ec31a4 = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x50, 0x4d, 0x4a, 0xc4, 0x30,
	0x14, 0xa6, 0xed, 0x8c, 0xe8, 0x1b, 0x54, 0x78, 0x20, 0x74, 0xca, 0x20, 0xa5, 0xab, 0xae, 0x12,
	0x18, 0x17, 0xde, 0xc0, 0xd9, 0x57, 0xc4, 0x75, 0xa6, 0x7d, 0x96, 0xa0, 0x49, 0xc6, 0xbc, 0x4c,
	0x45, 0xc4, 0x8d, 0x57, 0xf0, 0x68, 0x5e, 0xc1, 0x83, 0x48, 0xa3, 0x28, 0xa8, 0xb3, 0x7b, 0xdf,
	0x97, 0xef, 0x8f, 0xc0, 0xbc, 0x57, 0x81, 0x1e, 0xd4, 0xa3, 0xdc, 0x78, 0x17, 0x9c, 0xdc, 0x32,
	0x79, 0x16, 0xf1, 0x46, 0xec, 0x9d, 0x30, 0xba, 0xf5, 0x4e, 0xb0, 0x1f, 0x44, 0x7c, 0x29, 0x16,
	0xbd, 0x73, 0xfd, 0x1d, 0x49, 0xb5, 0xd1, 0x52, 0x59, 0xeb, 0x82, 0x0a, 0xda, 0xd9, 0x2f, 0x47,
	0x75, 0x01, 0x93, 0x2b, 0x26, 0x8f, 0x47, 0x90, 0xea, 0x2e, 0x4f, 0xca, 0xa4, 0xce, 0x9a, 0x54,
	0x77, 0x88, 0x30, 0xb1, 0xca, 0x50, 0x9e, 0x96, 0x49, 0x7d, 0xd0, 0xc4, 0x1b, 0x0b, 0xd8, 0xb7,
	0xba, 0xbd, 0x8d, 0x7c, 0x16, 0xf9, 0x6f, 0x5c, 0x2d, 0x00, 0x56, 0x14, 0x1a, 0xba, 0xdf, 0x12,
	0x87, 0xdf, 0x69, 0xd5, 0x39, 0x4c, 0xc7, 0x16, 0x46, 0x01, 0xd3, 0xb8, 0x2a, 0x4f, 0xca, 0xac,
	0x9e, 0x2d, 0x73, 0xf1, 0x77, 0xb0, 0x18, 0x95, 0xcd, 0xa7, 0x6c, 0x79, 0x03, 0xb3, 0x11, 0x5e,
	0x92, 0x1f, 0x74, 0x4b, 0x78, 0x0d, 0xd9, 0x8a, 0x02, 0x9e, 0xfe, 0x67, 0xfb, 0xa9, 0x2f, 0xe6,
	0xbb, 0x62, 0xb9, 0x3a, 0x79, 0x79, 0x7b, 0x7f, 0x4d, 0x8f, 0xf1, 0x50, 0x1a, 0x32, 0x6b, 0xf2,
	0x2c, 0x9f, 0x74, 0xf7, 0xbc, 0xde, 0x8b, 0xbf, 0x71, 0xf6, 0x11, 0x00, 0x00, 0xff, 0xff, 0xb9,
	0x4b, 0x56, 0xee, 0x5c, 0x01, 0x00, 0x00,
}
